name: Test

on:
  push:
  pull_request:

env:
  GO111MODULE: on

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose
